name: macOS Build

on:
  push:
    branches: '*'
    tags: '*'
  pull_request:
    types: [opened, reopened, synchronize, edited]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        os: [macos-latest]
        qt-version: ['6.4.2']
        qt-target: ['desktop']
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true
    ## Install Qt
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ matrix.qt-version }}
        host: 'mac'
        target: ${{ matrix.qt-target }}
    ## Build
    - name: Build
      run: |
        qmake
        make -j6
      shell: bash
